services:
  backend:
    container_name: advertising-platforms-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "8080:8080"
  seq:
    container_name: advertising-platforms-seq
    image: datalust/seq
    restart: no
    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_ADMINPASSWORD: secure
    ports:
      - "5341:80"
      - "5342:5341"