services:
  backend:
    container_name: advertising-platforms-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "7251:8080"
  seq:
    container_name: seq
    image: datalust/seq
    restart: no
    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_ADMINPASSWORD: secure
    ports:
      - 5341:80